app.py
import os
from flask import Flask, send_from_directory
from db_config import init_db, close_db
from routes.login import login_bp
from routes.register import reister_bp
from routes.index import index_bp
from routes.product import product_bp
from routes.cart import cart_bp

app = Flask(__name__)
app.secret_key = "abc"

app.teardown_appcontext(close_db)

app.register_blueprint(product_bp)
app.register_blueprint(index_bp)
app.register_blueprint(login_bp)
app.register_blueprint(reister_bp)
app.register_blueprint(cart_bp)

with app.app_context():
    init_db()

@app.route('/uploads/<filename>')
def uploaded_file(filename):
    return send_from_directory(os.path.join(app.root_path, 'uploads'), filename)

if __name__ == "__main__":
    app.run(debug=True, host="127.0.0.1", port=5000)

routes/cart.py
from flask import Blueprint, render_template, session, request, jsonify
from db_config import get_db

cart_bp = Blueprint('cart', __name__)

@cart_bp.route('/cart')
def cart(): 
    return render_template('layout/cart.html')

@cart_bp.route('/add-to-cart', methods=['POST'])
def add_to_cart():
    product_id = request.json.get('product_id')
    db = get_db()
    product = db.execute("SELECT * FROM product WHERE id = ?", (product_id,)).fetchone()
    cart = session.get('cart', [])
    found = False
    for item in cart:
        if item['id'] == product_id:
            item['qty'] += 1
            found = True
            break
    if not found:
        product_data = {
            'price': product['price'],
            'image': product['image'],
            'name': product['title'],
            'qty': 1,
            'id': product['id'],
        }
        cart.append(product_data)
    session['cart'] = cart

    return jsonify({'status': 'success', 'product': session['cart']})


@cart_bp.route('/show-cart')
def show_cart():
    cart = session.get('cart', [])
    return render_template('layout/cart.html', products=cart)

routes/index.py
from flask import render_template, Blueprint
from db_config import get_db

index_bp = Blueprint("index", __name__)


@index_bp.route("/")
def index():
    db = get_db()
    products = db.execute("SELECT * FROM product").fetchall()
    return render_template("index.html", products=products)

routes/login.py
import re
from flask import Blueprint, render_template, request, session, redirect, url_for
from db_config import get_db
from werkzeug.security import check_password_hash

login_bp = Blueprint("login", __name__)

def is_valid_email(email):
    pattern = r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.[a-zA-Z]{2,}$"
    return re.match(pattern, email) is not None


@login_bp.route("/login", methods=["GET", "POST"])
def login():
    errors = {}
    ketqua = ""
    email = request.form.get("email", "").strip()
    password = request.form.get("password", "").strip()
    if request.method == "POST":
        if not email:
            errors["email"] = "Vui long nhap Email"
        elif not is_valid_email(email):
            errors["email"] = "Email khong dung dinh dang"
        if not password:
            errors["password"] = "Vui long nhap Password"
        if not errors:
            db = get_db()
            user = db.execute(
                "SELECT * FROM users WHERE email = ?",(email,)).fetchone()
            if user and check_password_hash(user["password"], password):
                session["user_id"] = user["id"]
                session["email"] = user["email"]
                ketqua = "Đăng nhập thành công"
            else:
                ketqua = "Email hoặc mật khẩu không đúng"
    return render_template(
        "layout/login.html", errors=errors, email=email, password=password, ketqua=ketqua
    )

@login_bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('login.login'))

@login_bp.route('/account')
def account():
    return render_template('layout/account.html')

routes/product.py
import os
from flask import Blueprint, render_template, request, redirect, url_for, current_app, session
from db_config import get_db


product_bp = Blueprint('product', __name__)

@product_bp.route('/my-product')
def my_product():
    db = get_db()
    user_id = session.get('user_id')
    products = db.execute('SELECT * FROM product WHERE id_user = ?', (user_id,)).fetchall()
    return render_template('layout/my-product.html', products=products)

@product_bp.route('/add-product', methods=['GET', 'POST'])
def add_product():
    ketqua = ""
    if request.method == 'POST':
        title = request.form.get('title')
        price = request.form.get('price')
        file = request.files.get('image')
        id_user = session.get('user_id')
        db = get_db()
        db.execute('insert into product (title, price, image, id_user) values (?, ?, ?, ?)', (title, price, file.filename, id_user))
        db.commit()
        UPLOAD_FOLDER = os.path.join(current_app.root_path, 'uploads')
        if not os.path.exists(UPLOAD_FOLDER):
            os.makedirs(UPLOAD_FOLDER)
        file_path = os.path.join(UPLOAD_FOLDER, file.filename)
        file.save(file_path)
        return redirect(url_for('product.my_product'))
    return render_template('layout/add-product.html', ketqua=ketqua)
@product_bp.route('/edit-product/<int:id>', methods=['GET', 'POST'])
def edit_product(id):
    db = get_db()
    if request.method == 'POST':
        title = request.form.get('title')
        price = request.form.get('price')
        file = request.files.get('image')
        db.execute('UPDATE product SET title = ?, price = ?, image = ? WHERE id = ?', (title, price, file.filename, id))
        db.commit()
        return redirect(url_for('product.my_product'))
    product = db.execute('SELECT * FROM product WHERE id = ?', (id,)).fetchone()
    return render_template('layout/edit-product.html', product=product)

@product_bp.route('/delete-product/<int:id>')
def delete_product(id):
    db = get_db()
    db.execute('DELETE FROM product WHERE id = ?', (id,))
    db.commit()
    return redirect(url_for('product.my_product'))

routes/register.py
import os
import re
from flask import Blueprint, render_template, redirect, url_for, request, current_app
from db_config import get_db
from werkzeug.security import generate_password_hash, check_password_hash

reister_bp = Blueprint("register", __name__)
ALLOWED_EXTENSIONS = {"png", "jpg", "jpeg", "gif"}
MAX_FILE_SIZE_MB = 1


def alowed_file(filename):
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


def is_valid_email(email):
    pattern = r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.[a-zA-Z]{2,}$"
    return re.match(pattern, email) is not None


@reister_bp.route("/register", methods=["GET", "POST"])
def register():
    errors = {}
    ketqua = ""
    email = request.form.get("email", "").strip()
    password = request.form.get("password", "").strip()
    name = request.form.get("name", "").strip()
    files = request.files.get("avatar")
    if request.method == "POST":
        if not email:
            errors["email"] = "Vui long nhap email"
        elif not is_valid_email(email):
            errors["email"] = "Email khong dung dinh dang"
        if not password:
            errors["password"] = "Vui long nhap password"
        if not name:
            errors["name"] = "Vui long nhap name"
        upload_result = handle_file_upload(files)
        if not upload_result["success"]:
            errors["files"] = upload_result["error"]
        if not errors:
            ketqua = f"DANG KY THANH CONG"
            hashed_password = generate_password_hash(password)
            db = get_db()
            db.execute(
                "INSERT INTO users (email, password, name, avatar) values (?, ?, ?, ?)",
                (email, hashed_password, name, files.filename),
            )
            db.commit()
            UPLOAD_FOLDER = os.path.join(current_app.root_path, "uploads")
            if not os.path.exists(UPLOAD_FOLDER):
                os.makedirs(UPLOAD_FOLDER)
            file_path = os.path.join(UPLOAD_FOLDER, files.filename)
            files.save(file_path)
            return redirect(url_for("login.login"))
    return render_template(
        "layout/register.html",
        email=email,
        password=password,
        errors=errors,
        files=files,
        ketqua=ketqua,
    )


def handle_file_upload(files):
    result = {"success": False, "error": None}
    if not files or files.filename == "":
        result["error"] = "Vui long chon file"
        return result
    if not alowed_file(files.filename):
        result["error"] = f"File '{files.filename}' khong hop le."
        return result
    files.seek(0, os.SEEK_END)
    file_size = files.tell()
    files.seek(0)
    if file_size > MAX_FILE_SIZE_MB * 1024 * 1024:
        result["error"] = (
            f"File '{files.filename}' qua lon! chi cho phep toi da {MAX_FILE_SIZE_MB}MB."
        )
        return result
    result["success"] = True
    return result

templates/layout/account.html
{% include 'layout/header.html' %}

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Account</h2>
                    <div class="panel-group category-products" id="accordian">
                        <!--category-productsr-->
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a href="{{ url_for('login.account') }}">account</a>
                                </h4>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a href="{{ url_for('product.my_product') }}">My product</a>
                                </h4>
                            </div>
                        </div>
                    </div>
                    <!--/category-products-->
                </div>
            </div>
            <div class="col-sm-9">
                <div class="blog-post-area">
                    <h2 class="title text-center">Update user</h2>
                    <div class="signup-form">
                        <!--sign up form-->
                        <h2>New User Information!</h2>
                        <form action="#">
                            <input type="text" placeholder="Name" />
                            <input type="email" placeholder="Email Address" />
                            <input type="password" placeholder="Password" />
                            <button type="submit" class="btn btn-default">SUBMIT</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% include 'layout/footer.html' %}

templates/layout/add-product.html
{% include 'layout/header.html' %}

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Account</h2>
                    <div class="panel-group category-products" id="accordian">
                        <!--category-productsr-->
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a href="{{ url_for('login.account') }}">account</a>
                                </h4>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a href="{{ url_for('product.my_product') }}">My product</a>
                                </h4>
                            </div>
                        </div>
                    </div>
                    <!--/category-products-->
                </div>
            </div>
            <div class="col-sm-9">
                <div class="blog-post-area">
                    <h2 class="title text-center">ADD PRODUCTS</h2>
                    <div class="signup-form">
                        <!--sign up form-->
                        <h2>New Product</h2>
                        <form action="/add-product" method="POST" enctype="multipart/form-data">
                            <!-- <input type="text" placeholder="ID" name="id" value="{{id}}" /> -->
                            <input type="text" placeholder="Title" name="title" value="{{title}}" />
                            <input type="number" placeholder="Price" name="price" required step="0.01" />
                            <input type="file" style="background: none" name="image" value="{{file}}" />
                            <button type="submit" class="btn btn-default">ADD</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% include 'layout/footer.html' %}

templates/layout/cart.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>Danh sách sản phẩm</title>
    </head>

    <body>
        <h2>Danh sách sản phẩm</h2>
        <a href="/">+ Thêm sản phẩm</a>
        <br />
        <br />
        <table border="1" cellpadding="8">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Tên</th>
                    <th>Hình ảnh</th>
                    <th>Giá</th>
                    <th>Số lượng</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td>{{ product.id }}</td>
                    <td>{{ product.name }}</td>
                    <td>
                        {% if product.image %}
                        <img src="/uploads/{{ product.image }}" width="100" />
                        {% else %} Không có ảnh {% endif %}
                    </td>
                    <td>{{ product.price }}</td>
                    <td>{{ product.qty }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <!-- <h1><button class="add-btn" id="5">test ajax</button></h1> -->
        <a href="/show-cart">cart</a>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    </body>
</html>

templates/layout/header.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Document</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css') }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/prettyPhoto.css') }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/price-range.css') }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css') }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/responsive.css') }}" />
        <!--[if lt IE 9]>
            <script src="js/html5shiv.js"></script>
            <script src="js/respond.min.js"></script>
        <![endif]-->
        <link rel="shortcut icon" href="{{ url_for('static', filename='images/ico/favicon.ico') }}" />
        <link
            rel="apple-touch-icon-precomposed"
            sizes="144x144"
            href="{{ url_for('static', filename='images/ico/apple-touch-icon-144-precomposed.png') }}"
        />
        <link
            rel="apple-touch-icon-precomposed"
            sizes="114x114"
            href="{{ url_for('static', filename='images/ico/apple-touch-icon-114-precomposed.png') }}"
        />
        <link
            rel="apple-touch-icon-precomposed"
            sizes="72x72"
            href="{{ url_for('static', filename='images/ico/apple-touch-icon-72-precomposed.png') }}"
        />
        <link
            rel="apple-touch-icon-precomposed"
            href="{{ url_for('static', filename='images/ico/apple-touch-icon-57-precomposed.png') }}"
        />
    </head>
    <body>
        <header id="header">
            <!--header-->
            <div class="header_top">
                <!--header_top-->
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="contactinfo">
                                <ul class="nav nav-pills">
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-phone"></i>
                                            +2 95 01 88 821
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-envelope"></i>
                                            info@domain.com
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="social-icons pull-right">
                                <ul class="nav navbar-nav">
                                    <li>
                                        <a href="#"><i class="fa fa-facebook"></i></a>
                                    </li>
                                    <li>
                                        <a href="#"><i class="fa fa-twitter"></i></a>
                                    </li>
                                    <li>
                                        <a href="#"><i class="fa fa-linkedin"></i></a>
                                    </li>
                                    <li>
                                        <a href="#"><i class="fa fa-dribbble"></i></a>
                                    </li>
                                    <li>
                                        <a href="#"><i class="fa fa-google-plus"></i></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--/header_top-->

            <div class="header-middle">
                <!--header-middle-->
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 clearfix">
                            <div class="logo pull-left">
                                <a href="{{ url_for('index.index') }}"><img src="static/images/home/logo.png" alt="" /></a>
                            </div>
                            <div class="btn-group pull-right clearfix">
                                <div class="btn-group">
                                    <button
                                        type="button"
                                        class="btn btn-default dropdown-toggle usa"
                                        data-toggle="dropdown"
                                    >
                                        USA
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a href="">Canada</a></li>
                                        <li><a href="">UK</a></li>
                                    </ul>
                                </div>

                                <div class="btn-group">
                                    <button
                                        type="button"
                                        class="btn btn-default dropdown-toggle usa"
                                        data-toggle="dropdown"
                                    >
                                        DOLLAR
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a href="">Canadian Dollar</a></li>
                                        <li><a href="">Pound</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-8 clearfix">
                            <div class="shop-menu clearfix pull-right">
                                <ul class="nav navbar-nav">
                                    {% if session['user_id'] %}
                                    <li>
                                        <a href="{{ url_for('login.account') }}">
                                            <i class="fa fa-user"></i>
                                            Account
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{{ url_for('cart.cart') }}">
                                            <i class="fa fa-shopping-cart"></i>
                                            Cart
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{{ url_for('login.logout') }}">
                                            <i class="fa fa-lock"></i>
                                            Logout
                                        </a>
                                    </li>
                                    {% else %}
                                    <li>
                                        <a href="{{ url_for('register.register') }}">
                                            <i class="fa fa-crosshairs"></i>
                                            Register
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{{ url_for('login.login') }}">
                                            <i class="fa fa-lock"></i>
                                            Login
                                        </a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--/header-middle-->

            <div class="header-bottom">
                <!--header-bottom-->
                <div class="container">
                    <div class="row">
                        <div class="col-sm-9">
                            <div class="navbar-header">
                                <button
                                    type="button"
                                    class="navbar-toggle"
                                    data-toggle="collapse"
                                    data-target=".navbar-collapse"
                                >
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                            </div>
                            <div class="mainmenu pull-left">
                                <ul class="nav navbar-nav collapse navbar-collapse">
                                    <li><a href="{{ url_for('index.index') }}" class="active">Home</a></li>
                                    <li class="dropdown">
                                        <a href="#">
                                            Shop
                                            <i class="fa fa-angle-down"></i>
                                        </a>
                                        <ul role="menu" class="sub-menu">
                                            <li><a href="shop.html">Products</a></li>
                                            <li>
                                                <a href="product-details.html">Product Details</a>
                                            </li>
                                            <li><a href="checkout.html">Checkout</a></li>
                                            <li><a href="cart.html">Cart</a></li>
                                            <li><a href="login.html">Login</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#">
                                            Blog
                                            <i class="fa fa-angle-down"></i>
                                        </a>
                                        <ul role="menu" class="sub-menu">
                                            <li><a href="blog.html">Blog List</a></li>
                                            <li><a href="blog-single.html">Blog Single</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="404.html">404</a></li>
                                    <li><a href="contact-us.html">Contact</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="search_box pull-right">
                                <input type="text" placeholder="Search" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--/header-bottom-->
        </header>

        <!-- Goi js vao day (neuco) -->
        <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery.scrollUp.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/price-range.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery.prettyPhoto.js') }}"></script>
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    </body>
</html>

templates/layout/my-product.html
{% include 'layout/header.html' %}

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Account</h2>
                    <div class="panel-group category-products" id="accordian">
                        <!--category-productsr-->
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a href="{{ url_for('login.account') }}">account</a>
                                </h4>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a href="{{ url_for('product.my_product') }}">My product</a>
                                </h4>
                            </div>
                        </div>
                    </div>
                    <!--/category-products-->
                </div>
            </div>
            <div class="col-sm-9">
                <div class="table-responsive cart_info">
                    <table class="table table-condensed">
                        <thead>
                            <tr class="cart_menu">
                                <td class="image">image</td>
                                <td class="description">name</td>
                                <td class="price">price</td>
                                <td class="total">action</td>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- <tr>
                                        <td class="cart_product">
                                            <a href=""><img src="static/images/cart/one.png" alt="" /></a>
                                        </td>
                                        <td class="cart_description">
                                            <h4><a href="">Colorblock Scuba</a></h4>
                                        </td>
                                        <td class="cart_price">
                                            <p>$59</p>
                                        </td>

                                        <td class="cart_total">
                                            <a>edit</a>
                                            <a>delete</a>
                                        </td>
                                    </tr> -->
                            {% for product in products %}
                            <tr>
                                <td class="cart_product">
                                    {% if product.image %}
                                    <img src="{{ url_for('uploaded_file', filename=product['image']) }}" width="100" />
                                    {% else %} Không có ảnh {% endif %}
                                </td>
                                <td class="cart_description">
                                    <h4><a href="">{{ product.title }}</a></h4>
                                </td>
                                <td class="cart_price">
                                    <p>{{ product.price }}</p>
                                </td>
                                <td class="cart_total">
                                    <a href="{{ url_for('product.edit_product', id=product.id) }}">edit</a>
                                    |
                                    <a
                                        href="{{ url_for('product.delete_product', id=product.id) }}"
                                        onclick="return confirm('Are you sure to delete?');"
                                    >
                                        delete
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <a href="{{ url_for('product.add_product') }}" class="btn btn-default">ADD</a>
                </div>
            </div>
        </div>
    </div>
</section>

{% include 'layout/footer.html' %}